### ISSUE TITLE
Dropdown doesn't open using bootstrap 5.1.3

### ISSUE THREAD

**Issue by Maid-Sabanovic** [ZakiMohammed/ng-bootstrap-5-dropdown-app#1]
Hi I tried your example only with Angular13 and bootstrap 5.1.3 and the dropdown doesn't open when clicking on it. I get no errors and I included styles and scripts like you did

**Comment by ZakiMohammed** [comment]
Hi @Maid-Sabanovic, I have to check with Bootstrap 5.1.3. The article is written way back with Bootstrap 5.0.0-alpha2, I will check and let you know. Thanks :)

**Comment by Maid-Sabanovic** [comment]
> Hi @Maid-Sabanovic, I have to check with Bootstrap 5.1.3. The article is written way back with Bootstrap 5.0.0-alpha2, I will check and let you know. Thanks :)

I got this working now, posted on stackoverflow: https://stackoverflow.com/questions/71080712/bootstrap-5-dropdown-doesnt-open-using-angular13/71080812#71080812

Thanks for reply!

**Comment by ZakiMohammed** [comment]
Yay! It is good, you found the solution. Read your answer, some silly data attributes and classes mismatch between versions.
